export enum AppActionTypes {
  TOGGLE_VISUALLY_IMPAIRED = "TOGGLE_VISUALLY_IMPAIRED",
}

export enum WeatherActionTypes {
  SEARCH_WEATHER_INITIALIZING_TOGGLE = "SEARCH_WEATHER_INITIALIZING_TOGGLE",
  SEARCH_WEATHER_SET = "SEARCH_WEATHER_SET",
  SEARCH_WEATHER_ERROR_TOGGLE = "SEARCH_WEATHER_ERROR_TOGGLE",
}
